git:
  depth: 3

jobs:
  include:
    - name: Android tests, stable channel
      os: linux
      dist: trusty
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
          - build-tools-29.0.2
          - android-29
      script: "./tool/travis_android_script.sh"
      env: FLUTTER_VERSION=stable

    - name: Flutter tests, stable channel
      os: linux
      dist: trusty
      language: ruby
      script: "./tool/travis_flutter_script.sh"
      env: FLUTTER_VERSION=stable


    - name: Android tests, beta channel
      os: linux
      dist: trusty
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
          - build-tools-29.0.2
          - android-29
      script: "./tool/travis_android_script.sh"
      env: FLUTTER_VERSION=beta

    - name: Flutter tests, beta channel
      os: linux
      dist: trusty
      language: ruby
      script: "./tool/travis_flutter_script.sh"
      env: FLUTTER_VERSION=beta


env:
  global:
    # Disabling this makes it easier to install our own copy of gcloud
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_script:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - "./flutter/bin/flutter doctor"


branches:
  only:
    - main
    - dev




