git:
  depth: 3

jobs:
  include:
    - name: iOS tests, stable channel
      os: osx
      osx_image: xcode11.2
      language: objective-c
      script: "./tool/travis_ios_script.sh"
      env: FLUTTER_VERSION=stable

    - name: Android tests, stable channel
      os: linux
      dist: trusty
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
          - build-tools-29.0.2
          - android-29
      script: "./tool/travis_android_script.sh"
      env: FLUTTER_VERSION=stable

    - name: Flutter tests, stable channel
      os: linux
      dist: trusty
      language: ruby
      script: "./tool/travis_flutter_script.sh"
      env: FLUTTER_VERSION=stable

    - name: iOS tests, beta channel
      os: osx
      osx_image: xcode11.2
      language: objective-c
      script: "./tool/travis_ios_script.sh"
      env: FLUTTER_VERSION=beta

    - name: Android tests, beta channel
      os: linux
      dist: trusty
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
          - build-tools-29.0.2
          - android-29
      script: "./tool/travis_android_script.sh"
      env: FLUTTER_VERSION=beta

    - name: Flutter tests, beta channel
      os: linux
      dist: trusty
      language: ruby
      script: "./tool/travis_flutter_script.sh"
      env: FLUTTER_VERSION=beta

    - name: Visual samples index tests
      os: linux
      dist: trusty
      env: FLUTTER_VERSION=stable
      script:
        - cd web/samples_index
        - ../../flutter/bin/dart pub get
        - ../../flutter/bin/dart test

  allow_failures:
    - env: FLUTTER_VERSION=beta

env:
  global:
    # Disabling this makes it easier to install our own copy of gcloud
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_script:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - "./flutter/bin/flutter doctor"
  - chmod +x tool/travis_*_script.sh

cache:
  cocoapods: true
  directories:
    - "$HOME/shared/.pub-cache"
    - "$HOME/google-cloud-sdk"

notifications:
  email: brogdon+github@gmail.com

branches:
  only:
    - master
    - beta
    - testing_sample



n