git:
  depth: 3




env:
  global:
    # Disabling this makes it easier to install our own copy of gcloud
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_script:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - "./flutter/bin/flutter doctor"


branches:
  only:
    - main
    - dev




